# Generated by Django 4.0.1 on 2022-05-13 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassangerPersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_full_name', models.CharField(max_length=200)),
                ('personal_age', models.IntegerField()),
                ('seat_id', models.IntegerField()),
                ('seat_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PassangerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_total_count', models.IntegerField()),
                ('seat_count_by_SL', models.IntegerField()),
                ('seat_count_by_1A', models.IntegerField()),
                ('seat_count_by_2A', models.IntegerField()),
                ('seat_count_by_3A', models.IntegerField()),
                ('seat_price_by_SL', models.IntegerField()),
                ('seat_price_by_1A', models.IntegerField()),
                ('seat_price_by_2A', models.IntegerField()),
                ('seat_price_by_3A', models.IntegerField()),
                ('passenger_personal_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.passangerpersonaldata')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
