# Generated by Django 4.0.1 on 2022-05-21 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userCreations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=' ', max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=1800)),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.ImageField(default='—Pngtree—blue default avatar_5938444.png', upload_to='images/')),
                ('is_above_18', models.BooleanField(default=False)),
                ('phone_no', models.IntegerField(default='00000')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('otp', models.CharField(default='00000', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='userAddon_saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default='—Pngtree—blue default avatar_5938444.png', upload_to='images/')),
                ('phone_no', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=100, null=True)),
                ('is_above_18', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
