# Generated by Django 3.2.9 on 2021-12-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
