# Generated by Django 3.2.9 on 2021-12-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211221_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(upload_to='images/<bound method Field.value_to_string of <django.db.models.fields.CharField>>'),
        ),
    ]
