# Generated by Django 3.2.9 on 2021-12-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(upload_to='images/<bound method CharField.get_prep_value of <django.db.models.fields.CharField>>'),
        ),
    ]
