# Generated by Django 3.2.9 on 2021-12-25 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default='—Pngtree—blue default avatar_5938444.png', upload_to='images/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_above_18', models.BooleanField(default=False)),
                ('gender', models.CharField(default='Male', max_length=1)),
                ('phone_no', models.IntegerField(max_length=12)),
                ('address', models.CharField(default='', max_length=100, null=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userCreations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=10, unique=True)),
                ('profile', models.ImageField(default='—Pngtree—blue default avatar_5938444.png', upload_to='images/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_above_18', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('otp', models.CharField(default='00000', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
