# Generated by Django 3.2.9 on 2021-12-30 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0008_auto_20211225_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='passanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='userAddon_saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default='—Pngtree—blue default avatar_5938444.png', upload_to='images/')),
                ('phone_no', models.IntegerField(max_length=12)),
                ('is_above_18', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('otp', models.CharField(default='00000', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usercreations',
            name='phone_no',
            field=models.IntegerField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercreations',
            name='passwd',
            field=models.CharField(max_length=800),
        ),
        migrations.DeleteModel(
            name='userAddon',
        ),
    ]
