# Generated by Django 3.2.9 on 2022-01-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20220102_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreations',
            name='user_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
