# Generated by Django 3.2.9 on 2022-01-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_usercreations_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreations',
            name='user_name',
            field=models.CharField(default=' ', max_length=30, unique=True),
        ),
    ]
