# Generated by Django 4.0.1 on 2022-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_usercreations_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddon_saving',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercreations',
            name='phone_no',
            field=models.IntegerField(default='00000'),
        ),
    ]
