# Generated by Django 4.0.1 on 2022-05-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_useraddon_saving_phone_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passanger',
        ),
    ]
