# Generated by Django 4.0.1 on 2022-05-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quotaPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seat_1A', models.FloatField(default=10)),
                ('Seat_2A', models.FloatField(default=10)),
                ('Seat_3A', models.FloatField(default=10)),
                ('Seat_SL', models.FloatField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='StationCodeMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Station_Code', models.CharField(max_length=30, unique=True)),
                ('Station_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='trainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Train_No', models.IntegerField()),
                ('Seat_1A', models.IntegerField(default=0)),
                ('Seat_2A', models.IntegerField(default=0)),
                ('Seat_3A', models.IntegerField(default=0)),
                ('Seat_SL', models.IntegerField(default=0)),
                ('Station_Name', models.CharField(max_length=30)),
                ('Station_Code', models.CharField(max_length=30)),
                ('Route_Number', models.CharField(max_length=30)),
                ('Arrival_time', models.TimeField()),
                ('Departure_Time', models.TimeField()),
                ('Distance', models.IntegerField(default=0)),
            ],
        ),
    ]
