# Generated by Django 4.0.1 on 2022-04-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_traininfo_trainroutepath_trainroutetime_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trainInfo',
            new_name='trainRecord',
        ),
    ]
