# Generated by Django 4.0.1 on 2022-04-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_rename_traininfo_trainrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trainRecord',
        ),
        migrations.DeleteModel(
            name='trainRoutePath',
        ),
        migrations.DeleteModel(
            name='trainRouteTime',
        ),
    ]
