# Generated by Django 4.0.1 on 2022-04-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train', '0004_delete_trainrecord_delete_trainroutepath_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainRoutePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_station_1', models.CharField(max_length=30)),
                ('train_station_2', models.CharField(max_length=30)),
                ('train_station_3', models.CharField(max_length=30)),
                ('train_station_4', models.CharField(max_length=30)),
                ('train_station_5', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='trainRouteTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_time_starting', models.DateTimeField()),
                ('train_time_1', models.DateTimeField()),
                ('train_time_2', models.DateTimeField()),
                ('train_time_3', models.DateTimeField()),
                ('train_time_4', models.DateTimeField()),
                ('train_time_5', models.DateTimeField()),
                ('train_time_destination', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='trainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.IntegerField(unique=True)),
                ('train_name', models.CharField(max_length=30)),
                ('train_starting', models.CharField(max_length=30)),
                ('train_destination', models.CharField(max_length=30)),
                ('route_path_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='train.trainroutepath')),
                ('route_time_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='train.trainroutetime')),
            ],
        ),
    ]
