# Generated by Django 4.0.1 on 2022-04-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_quotaprice_trainrecord_train_ac_seat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quotaPrice',
        ),
        migrations.DeleteModel(
            name='trainRecord',
        ),
        migrations.DeleteModel(
            name='trainRoutePath',
        ),
        migrations.DeleteModel(
            name='trainRouteTime',
        ),
    ]
