# Generated by Django 4.0.1 on 2022-04-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainrecord',
            name='route_path_id',
        ),
        migrations.RemoveField(
            model_name='trainrecord',
            name='route_time_id',
        ),
        migrations.RemoveField(
            model_name='trainrecord',
            name='train_ac_seat',
        ),
        migrations.RemoveField(
            model_name='trainrecord',
            name='train_destination',
        ),
        migrations.RemoveField(
            model_name='trainrecord',
            name='train_general_seat',
        ),
        migrations.RemoveField(
            model_name='trainrecord',
            name='train_name',
        ),
        migrations.RemoveField(
            model_name='trainrecord',
            name='train_no',
        ),
        migrations.RemoveField(
            model_name='trainrecord',
            name='train_seat_seat',
        ),
        migrations.RemoveField(
            model_name='trainrecord',
            name='train_sleeper_seat',
        ),
        migrations.RemoveField(
            model_name='trainrecord',
            name='train_start_date',
        ),
        migrations.RemoveField(
            model_name='trainrecord',
            name='train_starting',
        ),
        migrations.RemoveField(
            model_name='trainrecord',
            name='train_total_seat',
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='Arrival_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='Departure_Time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='Distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='Route_Number',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='Seat_1A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='Seat_2A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='Seat_3A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='Seat_SL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='Station_Code',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='Station_Name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='Train_No',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='trainRoutePath',
        ),
        migrations.DeleteModel(
            name='trainRouteTime',
        ),
    ]
