# Generated by Django 4.0.1 on 2022-04-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0009_remove_trainrecord_route_path_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainrecord',
            name='Train_No',
            field=models.IntegerField(),
        ),
    ]
