# Generated by Django 4.0.1 on 2022-05-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0010_alter_trainrecord_train_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotaprice',
            name='Ac',
        ),
        migrations.RemoveField(
            model_name='quotaprice',
            name='Seat',
        ),
        migrations.RemoveField(
            model_name='quotaprice',
            name='general',
        ),
        migrations.RemoveField(
            model_name='quotaprice',
            name='sleeper',
        ),
        migrations.AddField(
            model_name='quotaprice',
            name='Seat_1A',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quotaprice',
            name='Seat_2A',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quotaprice',
            name='Seat_3A',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quotaprice',
            name='Seat_SL',
            field=models.FloatField(default=10),
        ),
    ]
